//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAppCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerRequest()
        {
            this.PartnerRequestList = new HashSet<PartnerRequestList>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Partner { get; set; }
    
        public virtual Partner Partner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRequestList> PartnerRequestList { get; set; }
    }
}
