//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAppCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerRequestList
    {
        public int ID { get; set; }
        public Nullable<int> PartnerRequest { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual PartnerRequest PartnerRequest1 { get; set; }

        public override string ToString()
        {
            return Convert.ToString(Product1);
        }
    }
}
