//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAppCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PartnerRequestList = new HashSet<PartnerRequestList>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Article { get; set; }
        public Nullable<double> MinCostForPartner { get; set; }
        public Nullable<int> ProductType { get; set; }
        public Nullable<int> Material { get; set; }
    
        public virtual Material Material1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRequestList> PartnerRequestList { get; set; }
        public virtual ProductType ProductType1 { get; set; }

        public override string ToString()
        {
            return ProductName;
        }
    }
}
